version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yngWIE500
      MYSQL_DATABASE: simple_project
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=yngWIE500
      - DB_NAME=simple_project
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    networks:
      - my-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
